server:
  port: 10080
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-service
          uri: lb://admin
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<path>.*), /$\{path}
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<path>.*), /$\{path}

logging.level.com.netflix: DEBUG

management:
  security:
    enabled: false
#    loadbalancer:
#      ribbon:
#        enabled: false
#    config:
#      server:
#        git:
#          uri: https://github.com/kevinatgz/spring-cloud-study
#          search-paths: config-repo
#    bus:
#      enabled: true
#      trace:
#        enabled: true

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh